# Generated by Django 5.1 on 2024-08-18 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=30)),
                ('hallticket', models.CharField(max_length=30)),
                ('clgname', models.CharField(max_length=30)),
                ('aadharno', models.CharField(max_length=30)),
                ('mobile', models.CharField(max_length=30)),
                ('amount', models.CharField(max_length=30)),
            ],
        ),
    ]
